<?php

// 'member_type',
//         // 'role_id',
//         // 'facebook_id',
//         // 'google_id',
//         'email',
//         'first_name',
//         'last_name',
//         // 'telephone',
//         'mobile',
//         'birthday',
//         'gender',
//         // 'country',
//         // 'address',
//         'province',
//         // 'district',
//         // 'subdistrict',
//         // 'postal_code',
//         // 'soi',
//         // 'road',
//         // 'building_type',
//         // 'id_card_no',
//         // 'img_profile',
//         // 'path',
//         // 'lastlogin_ip',
//         'confirm_email',
//         'status',
return [
    [
        'name' => 'id',
        'label' => 'id',
        'id' => 'id',
        'type' => 'text',
        'required' => 'required',
        'placeholder' => 'please insert id',
    ], [
        'name' => 'member_type',
        'label' => 'member_type',
        'id' => 'member_type',
        'type' => 'text',
        'required' => 'required',
        'placeholder' => 'please insert member_type',
    ], [
        'name' => 'email',
        'label' => 'email',
        'id' => 'email',
        'type' => 'text',
        'required' => 'required',
        'placeholder' => 'please insert email',
    ], [
        'name' => 'mobile',
        'label' => 'mobile',
        'id' => 'mobile',
        'type' => 'text',
        'required' => 'required',
        'placeholder' => 'please insert mobile',
    ], [
        'name' => 'mobile',
        'label' => 'mobile',
        'id' => 'mobile',
        'type' => 'text',
        'required' => 'required',
        'placeholder' => 'please insert mobile',
    ],

    [
        'name' => 'status',
        'label' => 'status',
        'id' => 'status',
        'type' => 'select',
        'placeholder' => 'please select status',
        'select' => [
            'displayname' => 'select status',
            'list' => [
                'pending' => 'pending',
                'verify' => 'verify',
                'process' => 'process',
                'activated' => 'activated',
                'unactivated' => 'unactivated',
            ],
        ],
    ], [
        'name' => 'confirm_email',
        'label' => 'confirm_email',
        'id' => 'confirm_email',
        'type' => 'select',
        'placeholder' => 'please select confirm_email',
        'select' => [
            'displayname' => 'select confirm_email',
            'list' => [
                'yes' => 'yes',
                'no' => 'no',
            ],
        ],
    ],
    [
        'name' => 'created_at',
        'label' => 'created_at',
        'id' => 'created_at',
        'type' => 'daterange',
        'required' => 'required',
        'placeholder' => 'please insert created_at',
    ],
];
